### PR TITLE
add speculative decoding example

### PR DESCRIPTION
**Pull request by XiaobingSuper**
This PR is about adding a speculative decoding example.

### CODE REVIEW

**Comment by XiaobingSuper** [comment]
@Shixiaowei02, could you help review this PR?

**Comment by avianion** [comment]
@XiaobingSuper did you test that this actually works?

**Comment by XiaobingSuper** [comment]
> @XiaobingSuper did you test that this actually works?

Yes, I checked and it works.

**Comment by biaochen** [comment]
Hi Xiaobing, great job! I've done similar things as you do, and sucessfully run sps (speculative sampling). It works fine for tp=1, but when tp=4 tritonserver will occasionlly block, and no log is printed. Do you encounter similar issue? The issue is detailed here:
https://github.com/triton-inference-server/tensorrtllm_backend/issues/498

Thanks~

**Pull request closed without merging**
